### ISSUE TITLE
 Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (2400) is outside the range (0.0, 1.0)

### ISSUE THREAD

**Issue by s9eenk** [stuartmatthews/leaflet-geotiff#4]
A DOM Exception is raised while rendering the page . Tried to go through the plotty.js file, but don't know where to change the range.

Any help is appreciated . Thanks in advance.

**Comment by stuartmatthews** [comment]
Can you please post some example code?  Does this error occur when you are creating a custom color scale?

Here is the reference for [addColorStop](https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient/addColorStop) which is throwing the error.

**Comment by s9eenk** [comment]
Hi Mathews,
Exactly , this error occurs when creating a custom color scale. Here , is the code 
**plotty.js**
"res": {
      colors: ["#C1CDD7","#63AF61","#B3E287","#F6EB1A","#F1A56A","#F46F16"],
      positions: [0,1367,2734,4100,5467]
    }
   **map.html**
   L.leafletGeotiff(
            url='qasz.tif',
            options={
                 band: 1,
                displayMin: 0,
                displayMax: 6000,
                name: 'Sample',
                colorScale: 'res'
            }
        ).addTo(mymap);
 Note: The pixel values ranges from 0 to 6000.

**Comment by stuartmatthews** [comment]
The positions array needs to be values from 0 to 1, as per the doc, and must have the same number of entries as the `colors` array, e.g. `[0, 0.2, 0.4, 0.6, 0.8, 0.1]`

**Comment by s9eenk** [comment]
Done the same thing what you have suggested but it throws in the console like "mymap is off screen ".  I don't know, whether any changes should be done to GeoTIFF File or any prerequisites before using it with 'leaflet-geotiff'

**Comment by s9eenk** [comment]
Works !. Great . Thanks Matthews. :+1:
